const PirateFirstName = new Map([
    ["A", "DIRTY"],
    ["B", "SQUIDLIPS"],
    ["C", "GORMLESS"],
    ["D", "SALTY"],
    ["E", "GRUMPY"],
    ["F", "PEG-LEG"],
    ["G", "RASCAL"],
    ["H", "TWO-TOE"],
    ["I", "FISHFACE"],
    ["J", "STINKY"],
    ["K", "JOLLY"],
    ["L", "PLUNDERIN'"],
    ["M", "FOOLISH"],
    ["N", "MISS"],
    ["O", "CRAZY"],
    ["P", "IRONHOOK"],
    ["Q", "CRINGY"],
    ["R", "USELESS"],
    ["S", "SIDEKICK"],
    ["T", "STARVIN'"],
    ["U", "SASSY"],
    ["V", "ONE-EAR"],
    ["W", "UGLY"],
    ["X", "SNOLLYGOSTER"],
    ["Y", "FEARLESS"],
    ["Z", "LICKSPITTLE"],
    ["Å", "SLOPPY"],
    ["Ä", "RUTHLESS"],
    ["Ö", "LANDLUBBER"],
])


export default PirateFirstName