const PirateLastName = new Map([
    ["A", "BLACKBEARD"],
    ["B", "JACK"],
    ["C", "BLUEBEARD"],
    ["D", "WET BONES"],
    ["E", "DARK-SKULL"],
    ["F", "PETE"],
    ["G", "SQUIFFY"],
    ["H", "TUNA-BREATH"],
    ["I", "MADMAN"],
    ["J", "SEAWEED"],
    ["K", "O'MALLEY"],
    ["L", "MAMA"],
    ["M", "SWASHBUCKLER"],
    ["N", "SEADOG"],
    ["O", "PUFFYPANTS"],
    ["P", "IRONHOOK"],
    ["Q", "SMELLY-CRAB"],
    ["R", "LAND-LOVER"],
    ["S", "TREASURE-JOE"],
    ["T", "SILVER-PANTS"],
    ["U", "FISH-BONE"],
    ["V", "MOONSCAR"],
    ["W", "JONES VON FISHY"],
    ["X", "SPARROW"],
    ["Y", "MCSWAGGER"],
    ["Z", "SLIMEBUCKET"],
    ["Å", "MCSTUBBY"],
    ["Ä", "LOBSTER-LEG"],
    ["Ö", "STINKY-BREATH"],
])


export default PirateLastName